#!/bin/bash
echo "=== GIT CHEAT SHEET ==="
echo ""
echo "START:"
echo "  git init              - Start repository"
echo "  git add file.txt      - Stage file"
echo "  git commit -m msg     - Save changes"
echo ""
echo "VIEW:"
echo "  git status            - What changed?"
echo "  git diff              - See differences"
echo "  git log               - History"
echo ""
echo "BRANCH:"
echo "  git branch            - List branches"
echo "  git checkout -b name  - Create branch"
echo "  git merge branch      - Combine branches"
echo ""
echo "REMOTE:"
echo "  git remote add origin URL  - Connect"
echo "  git push             - Upload"
echo "  git pull             - Download"
